-- CreateEnum
CREATE TYPE "Status" AS ENUM ('PROJECT_CREATING', 'PROJECT_INITIALIZING', 'PROJECT_INITIALIZED', 'RETRIEVING_PROVIDER', 'INSTALLING_PROVIDER', 'PROVIDER_INSTALLED');

-- AlterTable
ALTER TABLE "Project" ADD COLUMN     "status" "Status" NOT NULL DEFAULT 'PROJECT_CREATING';
